export const SEARCH_ALL_LOCALIDADES_START = "SEARCH_ALL_LOCALIDADES_START";
export const SEARCH_ALL_LOCALIDADES_ERROR = "SEARCH_ALL_LOCALIDADES_ERROR";
export const SEARCH_ALL_LOCALIDADES_COMPLETE =
  "SEARCH_ALL_LOCALIDADES_COMPLETE";
