export const SEARCH_ALL_LOCALIDADES_START = "SEARCH_ALL_LOCALIDADES_START";
export const SEARCH_ALL_LOCALIDADES_ERROR = "SEARCH_ALL_LOCALIDADES_ERROR";
export const SEARCH_ALL_LOCALIDADES_COMPLETE =
  "SEARCH_ALL_LOCALIDADES_COMPLETE";

export const UPDATE_LOCALIDADES_START = "UPDATE_LOCALIDADES_START";
export const UPDATE_LOCALIDADES_ERROR = "UPDATE_LOCALIDADES_ERROR";
export const UPDATE_LOCALIDADES_COMPLETE = "UPDATE_LOCALIDADES_COMPLETE";
