export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_COMPLETE = "LOGIN_USER_COMPLETE";

export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";
export const LOGOUT_USER_COMPLETE = "LOGOUT_USER_COMPLETE";
