export const SEARCH_ALL_PROJECTS_START = "SEARCH_ALL_PROJECTS_START";
export const SEARCH_ALL_PROJECTS_ERROR = "SEARCH_ALL_PROJECTS_ERROR";
export const SEARCH_ALL_PROJECTS_COMPLETE = "SEARCH_ALL_PROJECTS_COMPLETE";

export const FINALIZAR_PROYECTO_COMPLETE = "FINALIZAR_PROYECTO_COMPLETE";
export const FINALIZAR_PROYECTO_START = "FINALIZAR_PROYECTO_START";
export const FINALIZAR_PROYECTO_ERROR = "FINALIZAR_PROYECTO_ERROR";
