export const SEARCH_ALL_PROJECTS_START = "SEARCH_ALL_PROJECTS_START";
export const SEARCH_ALL_PROJECTS_ERROR = "SEARCH_ALL_PROJECTS_ERROR";
export const SEARCH_ALL_PROJECTS_COMPLETE = "SEARCH_ALL_PROJECTS_COMPLETE";
