export const SEARCH_DONATIONS_START = "SEARCH_DONATIONS_START";
export const SEARCH_DONATIONS_ERROR = "SEARCH_DONATIONS_ERROR";
export const SEARCH_DONATIONS_COMPLETE = "SEARCH_DONATIONS_COMPLETE";

export const DONACION_START = "DONACION_START";
export const DONACION_ERROR = "DONACION_ERROR";
export const DONACION_COMPLETE = "DONACION_COMPLETE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";
